version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./db:/app/db
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always