version: '3.8'

services:
  bot:
    image: ghcr.io/vyasma-mafia/mafia-onboarding-bot:main
    env_file:
      - .env
    volumes:
      - ./db:/app/db
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
